v0.4

diff --git a/opt/sltools/sltools b/opt/sltools/sltools
--- a/opt/sltools/sltools
+++ b/opt/sltools/sltools
@@ -16,33 +16,32 @@ Sent_Command() {
     screen -S "${slftp_screen_name}" -p 0 -X stuff "stop^M"
 }
 
-
-
 Run_SLFTP_Internal() {
     if [[ "$(screen -ls)" = *${slftp_screen_name}* ]]; then
-        Sent_Error "$(m_tr "(Err_001) slFTP: Already running.")"
+        Sent_Error  "004" "$(m_tr "slFTP: Already running.")"
     else
         [ "$(whoami)" != "${unix_user} " ] && su -l ${unix_user} -c "screen -dmS ${slftp_screen_name} /usr/bin/sltools-core run" || screen -dmS  ${slftp_screen_name} /usr/bin/sltools-core run
         retVal=$?
-        [ ${retVal} -ne 0 ] && Sent_Error "$(m_tr "(Err_002) Error starting slftp screen.")"
+        [ ${retVal} -ne 0 ] && Sent_Error  "005"  "$(m_tr "Error starting slftp screen.")"
         ps aux | grep ${unix_user} | grep ${slftp_screen_name}
     fi
 }
+
 Run_SLFTP() {
-    [[ $(readlink -f -- "${slftp_directory}"/"${slftp_binary_name}") == "" ]] && Sent_Error "$(m_tr "(Err_017) %s is missing.")" "${slftp_directory}"/"${slftp_binary_name}"
+    [[ $(readlink -f -- "${slftp_directory}"/"${slftp_binary_name}") == "" ]] && Sent_Error "006" "$(m_tr "%s is missing." "${slftp_directory}"/"${slftp_binary_name}")"
     cd "${slftp_directory}" || exit
     re='^[0-9]+$'
-    ! [[ ${start_reset_files} =~ ${re} ]] && Sent_Error "$(m_tr "(Err_020) Invalid value for option '%s' , check configuration file.")" "start_reset_files"
+    ! [[ ${start_reset_files} =~ ${re} ]] && Sent_Error "007" "$(m_tr "Invalid value for option '%s' , check configuration file." "start_reset_files")"
     [ "${reset_list}" != "" ] && rm -f "${reset_list}"
-    ! [[ "${slftp_restart_onfailure}" =~ ${re} ]] && Sent_Error "$(m_tr "(Err_020) Invalid value for option '%s' , check configuration file.")" "slftp_restart_onfailure"
+    ! [[ "${slftp_restart_onfailure}" =~ ${re} ]] && Sent_Error  "008" "$(m_tr "Invalid value for option '%s' , check configuration file." "slftp_restart_onfailure")"
     Run_SLFTP_Internal
     exit 1
 }
 
 Install_SLFTP() {
-    [ ! -d "/opt/src/slftp" ] && Sent_Error "$(m_tr "(Err_017) %s is missing.")" "/opt/src/slftp"
+    [ ! -d "/opt/src/slftp" ] && Sent_Error  "009" "$(m_tr "%s is missing." "/opt/src/slftp")"
     cd /opt/src/slftp || exit
-    [[ ! -f "/opt/src/slftp/Makefile" ]] && Sent_Error "$(m_tr "(Err_018) Code source need update for %s.")" "SLFTP"
+    [[ ! -f "/opt/src/slftp/Makefile" ]] && Sent_Error "010" "$(m_tr "Code source need update for %s." "SLFTP")"
     sed -i "s@SLFTPPATH = ~/slftp@SLFTPPATH = ${slftp_directory}@" /opt/src/slftp/Makefile
     [ ! -d "${slftp_directory}" ] && mkdir -p ${slftp_directory}
     make -s || exit
@@ -54,39 +53,49 @@ Install_SLFTP() {
 Missing_SLFTP() {
     Sent_Debug "[RUN] Missing_SLFTP"
     PS3="$(m_tr "Select the operation"): "
-    select opt in           \
-        "$(m_tr "Install manually")" \
-        "$(m_tr "Install automatically")" \
+    select opt in                           \
+        "$(m_tr "Install automatically")"   \
+        "$(m_tr "Install manually")"        \
         "$(m_tr "Quit")";
         do
-            case $opt in
+            case ${opt} in
                 "$(m_tr "Install automatically")") Install_SLFTP; sleep 2;;
-                "$(m_tr "Install manually")") Sent_MSG "$(m_tr "To install manually visit the URL address: %s")" "${URL_SITE_SLFTP}"; exit 0;;
+                "$(m_tr "Install manually")") Sent_MSG "$(m_tr "To install manually visit the URL address: %s" "${URL_SITE_SLFTP}")"; exit 0;;
                 "$(m_tr "Quit")") break;;
-                *) echo "$(m_tr "Invalid option") $REPLY";;
+                *) echo "$(m_tr "Invalid option") ${REPLY}";;
             esac
         done
     Sent_Debug "[OK] Missing_SLFTP"
 }
 
+Install_FPC() {
+    [ ! -d "/opt/src/fpc" ] && Sent_Error  "009" "$(m_tr "%s is missing." "/opt/src/fpc")"
+    cd /opt/src/fpc || exit
+    git submodule update --init
+    [[ ! -f "/opt/src/slftp/Makefile" ]] && Sent_Error "010" "$(m_tr "Code source need update for %s." "SLFTP")"
+    sed -i "s@SLFTPPATH = ~/slftp@SLFTPPATH = ${slftp_directory}@" /opt/src/slftp/Makefile
+    [ ! -d "${slftp_directory}" ] && mkdir -p ${slftp_directory}
+    make -s || exit
+    make install || exit
+    [ "${slftp_wide_system}" = 1 ] && ln -s "${slftp_directory}"/"${slftp_binary_name}" /usr/bin/
+
+}
+
 Missing_FPC() {
     Sent_Debug "[RUN] Missing_FPC"
-    if [[ "$(command -v fpc)" == "" ]]; then
-        Sent_Error "$(m_tr "(Err_015) FPC (Free Pascal Compiler) est manquant pour compiler slftp.")"
-          PS3="$(m_tr "Select the operation"): "
-        select opt in           \
-          "$(m_tr "Install manually")" \
-            "$(m_tr "Install automatically")" \
-          "$(m_tr "Quit")";
-        do
-            case $opt in
-                "$(m_tr "Install automatically")") Missing_FPC; sleep 2; Main_Menu; break;;
-                "$(m_tr "Install manually")") break;;
-                "$(m_tr "Quit")") break;;
-                *) echo "$(m_tr "Invalid option") $REPLY";;
-            esac
-        done
-    fi
+    PS3="$(m_tr "Select the operation"): "
+    select opt in                           \
+        "$(m_tr "Install automatically")"   \
+        "$(m_tr "Install manually")"        \
+        "$(m_tr "Quit")";
+    do
+        case ${opt} in
+            "$(m_tr "Install automatically")") Install_FPC; sleep 2; Main_Menu; break;;
+            "$(m_tr "Install manually")") Sent_MSG "$(m_tr "To install manually visit the URL address: %s" "${URL_SITE_FPC}")"; exit 0;;
+            "$(m_tr "Quit")") break;;
+            *) echo "$(m_tr "Invalid option") ${REPLY}";;
+        esac
+    done
     Sent_Debug "[OK] Missing_FPC"
 }
 
@@ -96,13 +105,13 @@ Menu_SLFTP () {
     banner "Menu SLFTP"
     Sent_Debug "[RUN] Menu_SLFTP"
     PS3="$(m_tr "Select the operation"): "
-    select opt in           \
-        "$(m_tr "Run")"       \
-        "$(m_tr "Stop")"       \
-        "$(m_tr "Join")"        \
-        "$(m_tr "Install")"     \
-        "$(m_tr "Update")"      \
-        "$(m_tr "Back to main menu")"      \
+    select opt in                       \
+        "$(m_tr "Run")"                 \
+        "$(m_tr "Stop")"                \
+        "$(m_tr "Join")"                \
+        "$(m_tr "Install")"             \
+        "$(m_tr "Update")"              \
+        "$(m_tr "Back to main menu")"   \
         "$(m_tr "Quit")"; do
         case ${opt} in
             "$(m_tr "Run")") Run_SLFTP; sleep 2; Main_Menu; break;;
@@ -120,9 +129,9 @@ Menu_FPC () {
     banner "Free Pascal Compiler"
     Sent_Debug "[RUN] Menu_FPC"
     PS3="$(m_tr "Select the operation"): "
-    select opt in           \
-        "$(m_tr "Install")"       \
-        "$(m_tr "Back to main menu")"      \
+    select opt in                       \
+        "$(m_tr "Install")"             \
+        "$(m_tr "Back to main menu")"   \
         "$(m_tr "Quit")"; do
         case ${opt} in
             "$(m_tr "Install")") Missing_FPC; sleep 2; Main_Menu; break;;
@@ -136,21 +145,21 @@ Menu_slTools () {
     banner "Menu SL-Tools"
     Sent_Debug "[RUN] Menu_slTools"
     PS3="$(m_tr "Select the operation"): "
-    select opt in           \
-        "$(m_tr "Config")"    \
-        "$(m_tr "Update")"    \
-        "$(m_tr "Info")"      \
-        "$(m_tr "Uninstall")" \
-        "$(m_tr "Back to main menu")"       \
+    select opt in                       \
+        "$(m_tr "Config")"              \
+        "$(m_tr "Update")"              \
+        "$(m_tr "Info")"                \
+        "$(m_tr "Uninstall")"           \
+        "$(m_tr "Back to main menu")"   \
         "$(m_tr "Quit")"; do
-        case $opt in
+        case ${opt} in
             "$(m_tr "Config")") echo "soon"; sleep 2; Main_Menu; break;;
             "$(m_tr "Update")") echo "soon"; sleep 2; Main_Menu; break;;
             "$(m_tr "Info")") echo "soon"; sleep 2; Main_Menu; break;;
             "$(m_tr "Uninstall")") echo "soon"; sleep 2; Main_Menu; break;;
             "$(m_tr "Back to main menu")") Main_Menu; break;;
             "$(m_tr "Quit")") break;;
-            *) echo "$(m_tr "Invalid option") $REPLY";;
+            *) echo "$(m_tr "Invalid option") ${REPLY}";;
         esac
     done
     Sent_Debug "[OK] Menu_slTools"
@@ -160,17 +169,17 @@ Main_Menu () {
     banner "Menu main"
     Sent_Debug "[RUN] Main_Menu"
     PS3="$(m_tr "Select the operation"): "
-    select opt in           \
-        "$(m_tr "Menu SLFTP")"    \
-        "$(m_tr "Menu SL-Tools")"    \
-        "$(m_tr "Menu cbFTP")"    \
+    select opt in                   \
+        "$(m_tr "Menu SLFTP")"      \
+        "$(m_tr "Menu SL-Tools")"   \
+        "$(m_tr "Menu cbFTP")"      \
         "$(m_tr "Quit")"; do
-        case $opt in
+        case ${opt} in
             "$(m_tr "Menu SLFTP")") Menu_SLFTP break;;
             "$(m_tr "Menu SL-Tools")") Menu_slTools break;;
             "$(m_tr "Menu cbFTP")") Menu_slTools break;;
             "$(m_tr "Quit")") break;;
-            *) echo "$(m_tr "Invalid option") $REPLY";;
+            *) echo "$(m_tr "Invalid option") ${REPLY}";;
         esac
     done
     Sent_Debug "[OK] Main_Menu"
diff --git a/opt/sltools/sltools-functions b/opt/sltools/sltools-functions
--- a/opt/sltools/sltools-functions
+++ b/opt/sltools/sltools-functions
@@ -1,7 +1,8 @@
 #!/usr/bin/env bash
 DEBUG=0
 LOG=1
-VER=0.3
+VER=0.4
+set -u 
 
 # Set magic variables for current file & dir
 __dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
@@ -9,8 +10,9 @@ __file="${__dir}/$(basename "${BASH_SOURCE[0]}")"
 __base="$(basename ${__file} .sh)"
 __root="$(cd "$(dirname "${__dir}")" && pwd)"
 
-m_tr() { 
-    echo $(gettext sltools "$1") 
+m_tr() {
+    local MSG=$(printf "$@")
+    echo $(gettext sltools "${MSG}") 
 }
 
 banner() {
@@ -66,8 +68,11 @@ Sent_MSG () {
 }
 
 Sent_Error() {
-    Sent_MSG  "$@"
-    if [ "$LOG" = 1 ]; then Sent_MSG "[$(date)] [ERROR] $*" >> "${FILE_LOG}"; fi
+    local ERR_CODE="$1"
+    shift
+    local ERR_MSG="$@ \n[ERR_${ERR_CODE}] $(m_tr "For more information visit: %s" "${URL_SLTOOLS}/wiki/error_${ERR_CODE}")"
+    Sent_MSG  "${ERR_MSG}"
+    if [ "${LOG}" = 1 ]; then Sent_MSG "[$(date)] [ERROR] ${ERR_MSG}" >> "${FILE_LOG}"; fi
     exit 0
 }
 
@@ -79,21 +84,30 @@ Sent_Debug() {
 Init() {
     URL_SLTOOLS="https://github.com/ZarTek-Creole/slTools"
     URL_SITE_SLFTP="https://gitlab.com/slftp/slftp"
-    BINS_NEEDED="echo printf grep cut tr tar touch su screen sudo gettext git"
-    FILE_CONF=/etc/slftp/sltools.cfg
-    FILE_CONF_DEF=/etc/slftp/sltools.cfg.dist
+    URL_SITE_FPC="https://www.freepascal.org"
+    BINS_NEEDED="echo printf grep cut tr tar touch su screen sudo gettext git make"
+    FILE_CONF=/etc/sltools/sltools.cfg
+    FILE_CONF_DEF=/etc/sltools/sltools.cfg.dist
     FILE_LOG=/var/log/sltools.log
     Sent_Debug "[OK] Init"
 }
-
+is_super_rigths() {
+    [[ $(is_user_root) -eq 0 ]] && [[ $(is_user_sudo) -eq 0 ]] && Sent_Error "001" "$(m_tr "A command requires higher rights such as root or sudo to continue. Start again with higher rights..")"
+}
 Init_Files() {
-    [ ! -f "${FILE_CONF}" ] && Sent_MSG $(m_tr "(Err_004) The following SL-Tools file is missing: '%s'. Creating the file ...") ${FILE_CONF} && mkdir -p "$(dirname "${FILE_CONF}")" && touch "${FILE_CONF}"
+    if [ ! -f "${FILE_CONF}" ]; then
+        [[ $(is_user_root) -eq 0 ]] && [[ $(is_user_sudo) -eq 0 ]] && Sent_Error "001" "$(m_tr "A command requires higher rights such as root or sudo to continue. Start again with higher rights..")"
+        Sent_MSG $(m_tr "(Err_004) The following SL-Tools file is missing: '%s'. Creating the file ..." "${FILE_CONF}") 
+        mkdir -p "$(dirname "${FILE_CONF}")"
+        touch "${FILE_CONF}"
+    fi 
     source "${FILE_CONF}"
     # Efface les anciens logs ...
-    [ -f "$FILE_LOG" ] && sudo rm "$FILE_LOG" && sudo touch "$FILE_LOG"
+    [ -f "$FILE_LOG" ] && sudo rm "$FILE_LOG" && sudo touch "$FILE_LOG" && sudo chmod 0666 "$FILE_LOG"
 }
 
 Init_Binary() {
+    local BINS_MISSING=""
     Sent_Debug "[RUN] Init_Binary"
     # check for needed bins
     for BIN in ${BINS_NEEDED}; do
@@ -105,19 +119,35 @@ Init_Binary() {
         fi
     done
     if [ -n "${BINS_MISSING}" ]; then
-        Sent_Error "$(m_tr "[!] Some binaries are missing:%s.Check dependencies on %s")" "${URL_SLTOOLS}" "${BINS_MISSING}"
+        Sent_Error "002" "$(m_tr "Some mandatory utilities are missing:%s." "${BINS_MISSING}")" 
 
     fi
     if [[ "$(command -v fpc)" == "" ]]; then
-        Sent_Error "$(m_tr "(Err_015) FPC (Free Pascal Compiler) is missing to compiler slftp.")"
+        banner "FPC (Free Pascal Compiler)"
+        Sent_MSG "$(m_tr "FPC (Free Pascal Compiler) is missing to compiler slftp.")"
+        printf '\n'
+        Missing_FPC
     fi
     if [[ "$(command -v "${slftp_binary_name}")" == "" ]] && [[ $(readlink -f -- "${slftp_directory}"/"${slftp_binary_name}") == "" ]]; then
         banner "SLFTP"
-        Sent_MSG "$(m_tr "(Err_016) %s is missing.")" "${slftp_binary_name}"
+        Sent_MSG "$(m_tr "%s is missing." "${slftp_binary_name}")" 
         printf '\n'
         Missing_SLFTP
     fi
     Sent_Debug "[OK] Init_Binary"
+}
+
+is_user_root () { 
+    [ "${EUID:-$(id -u)}" -eq 0 ] && return 0 || return 1
+}
+
+is_user_sudo () { 
+    sudo -v >/dev/null 2>&1
+    [ $? ] && return 1 || return 0
+}
+
+is_run_sudo () { 
+    [[ "${SUDO_USER:-}" = "" ]] && return 0 || return 1
 }
 
 Init_Config() {
@@ -137,13 +167,15 @@ Init_Config() {
 
 Config_Set_Value() {
     Sent_Debug "[RUN] Config_Set_Value $*"
-    [ ! -f ${FILE_CONF_DEF} ] && echo "creation de ${FILE_CONF_DEF}" && touch ${FILE_CONF_DEF}
-    [ ! -f ${FILE_CONF} ] && echo "creation de ${FILE_CONF}" && touch ${FILE_CONF}
+    
+    
+    [ ! -f ${FILE_CONF_DEF} ] && Sent_MSG $(m_tr "Creating file %s" "${FILE_CONF_DEF}") && touch "${FILE_CONF_DEF}" && chmod 0666 "${FILE_CONF_DEF}"
+    [ ! -f ${FILE_CONF} ] && Sent_MSG $(m_tr "Creating file %s" "${FILE_CONF}") && touch "${FILE_CONF}" && chmod 0666 "${FILE_CONF}"
     if [[ -f "${FILE_CONF}" && "$( grep -c -w "$1" ${FILE_CONF})" = 1 ]]; then
 	    value=$(grep -w "$1" ${FILE_CONF} | cut -d "=" -f2 | tr -d "\"")
     else
         value_default=$(cat ${FILE_CONF_DEF} | grep -w "$1" | cut -d "=" -f2 | tr -d "\"")
-        Sent_MSG "$(m_tr "Please enter the value for %s, default [ %s ] : ")" "$1" "${value_default}"; read -r value
+        Sent_MSG "$(m_tr "Please enter the value for %s, default [ %s ] : " "$1" "${value_default}")"; read -r value
     	[ "$value" = "" ] && value=${value_default}
     fi
     [ "$(grep -c -w "$1=" ${FILE_CONF} )" = 0 ] && echo "$1"=\""$value"\" >> ${FILE_CONF}
@@ -153,13 +185,13 @@ Config_Set_Value() {
 Config_Check_Value() {
     Sent_Debug "[RUN] Config_Check_Value $*"
     # test comment
-    [[ ! -v "$1" ]] && Sent_MSG "$(m_tr "(Err_005) The configuration of '%s=Value' is missing in %s")" "$1" "${FILE_CONF}" && Config_Set_Value "$1" 
+    [[ ! -v "$1" ]] && Sent_MSG "$(m_tr "The configuration of '%s=Value' is missing in %s" "$1" "${FILE_CONF}")" && Config_Set_Value "$1" 
     Sent_Debug "[OK] Config_Check_Value $*"
 }
 
 Init_Account_Unix() {
     if Unix_Group_Exists "${unix_group}"; then 
-        Sent_MSG "$(m_tr "The unix group '%s' does not exist, do you want to create it? [Y]es [N]o, default Y :")" "${unix_group}"; read -r create_group
+        Sent_MSG "$(m_tr "The unix group '%s' does not exist, do you want to create it? [Y]es [N]o, default Y :" "${unix_group}")"; read -r create_group
         case ${create_group} in
             [YyoO]) Unix_Group_Create;;
             [Nn]) exit 1 ;;
@@ -167,7 +199,7 @@ Init_Account_Unix() {
         esac
     fi
     if Unix_User_Exists "${unix_user}"; then 
-        Sent_MSG "$(m_tr "The unix user '%s' does not exist, do you want to create it? [Y]es [N]o, default Y :")" "${unix_user}"; read -r create_user
+        Sent_MSG "$(m_tr "The unix user '%s' does not exist, do you want to create it? [Y]es [N]o, default Y :" "${unix_user}")"; read -r create_user
         case ${create_user} in
             [YyoO]) Unix_User_Create;;
             [Nn]) exit 1 ;;
