trap

diff --git a/opt/sltools/sltools-functions b/opt/sltools/sltools-functions
--- a/opt/sltools/sltools-functions
+++ b/opt/sltools/sltools-functions
@@ -2,6 +2,13 @@
 DEBUG=0
 LOG=1
 VER=0.3
+
+# Set magic variables for current file & dir
+__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+__file="${__dir}/$(basename "${BASH_SOURCE[0]}")"
+__base="$(basename ${__file} .sh)"
+__root="$(cd "$(dirname "${__dir}")" && pwd)"
+
 m_tr() { 
     echo $(gettext sltools "$1") 
 }
@@ -44,6 +51,11 @@ trap ctrl_c INT
 ctrl_c() {
     echo " ** CTRL-C ..."
     exit 1
+}
+trap close_by_signal SIGINT SIGTERM ERR EXIT
+close_by_signal() {
+  trap - SIGINT SIGTERM ERR EXIT
+  # script cleanup here
 }
 
 Sent_MSG () {
